language: python
python:
  - "3.6"  # 3.7 development branch
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt
  - pip install ./sentinel2


script:
  - pytest